services:
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333" # HTTP
      - "6334:6334" # gRPC port
    volumes:
      - ./qdrant_storage:/qdrant/storage
    restart: unless-stopped #Auto restart container unless intentionalt stopped
